language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  # - sudo apt-get --quiet update7
  - sudo pip install --upgrade setuptools
install:
  - pip install -r requirements.txt
script:
  - python setup.py test